Repository Qiskit/qiskit-ibm-provider, pull requests merged in 2021-08, with the labels that each got.

#17 Specify program visibility with `is_public` parameter in `IBMRuntimeService.upload_program`
  qiskit_ibm/api/clients/runtime.py
  qiskit_ibm/api/rest/runtime.py
  qiskit_ibm/runtime/ibm_runtime_service.py
  qiskit_ibm/runtime/runtime_program.py
  releasenotes/notes/add-is_public-on-upload-program-5b5bb13912a8cf67.yaml
  test/ibmq/runtime/fake_runtime_client.py
  test/ibmq/runtime/test_runtime.py
  test/ibmq/runtime/test_runtime_integration.py
Labels: Changelog: New Feature

#33 Fix IBMQJobManager job set retrieval
  qiskit_ibm/managed/utils.py
  releasenotes/notes/fix-jm-re-24d71126c0a2f539.yaml
  test/ibmq/test_ibmq_jobmanager.py
Labels: Changelog: Bugfix

#35 Remove deprecated IBMQDeprecatedBackendService
  qiskit_ibm/accountprovider.py
  qiskit_ibm/ibmqbackendservice.py
  releasenotes/notes/remove-ibmqdeprecatedbackendservice-668f549558e21088.yaml
  test/ibmq/test_ibmq_backend.py
Labels: Changelog: Removal

#51 Remove job share level
  docs/tutorials/1_the_ibmq_account.ipynb
  qiskit_ibm/apiconstants.py
  qiskit_ibm/ibmqbackend.py
  qiskit_ibm/job/ibmqjob.py
  qiskit_ibm/managed/ibmqjobmanager.py
  qiskit_ibm/managed/managedjob.py
  qiskit_ibm/managed/managedjobset.py
  releasenotes/notes/remove-job-share-level-192957fbb716d077.yaml
Labels: Changelog: Removal

#52 Remove credential updater
  qiskit_ibm/apiconstants.py
  qiskit_ibm/credentials/updater.py
  qiskit_ibm/ibmqfactory.py
  releasenotes/notes/remove-credential-updater-43503285490965c5.yaml
  test/ibmq/test_registration.py
Labels: Changelog: Removal

#57 remove client_version setter
  qiskit_ibm/job/ibmqjob.py
  releasenotes/notes/remove-client-version-setter-0a0be0ef3112a879.yaml
Labels: Changelog: Removal
