Repository Qiskit/qiskit-ibm-provider, pull requests merged in 2021-10, with the labels that each got.

#120 Only print program summary in runtime pprint_programs()
  qiskit_ibm/runtime/ibm_runtime_service.py
  releasenotes/notes/runtime-pprint-programs-update-8d5d79aceeb49106.yaml
  test/ibm/runtime/test_runtime.py
Labels: Changelog: API Change

#49 Remove qobj (QasmQobj and PulseQobj) support in `backend.run`
  docs/tutorials/1_the_ibm_quantum_account.ipynb
  qiskit_ibm/ibm_backend.py
  qiskit_ibm/job/ibm_job.py
  qiskit_ibm/runtime/program/program_backend.py
  qiskit_ibm/utils/__init__.py
  qiskit_ibm/utils/qobj_utils.py
  releasenotes/notes/remove-backend-run-qobj-925942c64cb0ea82.yaml
  test/ibm/test_basic_server_paths.py
  test/ibm/test_ibm_backend.py
  test/ibm/test_ibm_integration.py
  test/ibm/test_ibm_job.py
  test/ibm/test_ibm_job_states.py
  test/ibm/test_random.py
  test/ibm/test_serialization.py
  test/utils.py
Labels: Changelog: Removal

#145 Check runtime job result cached by comparing to None
  qiskit_ibm/runtime/runtime_job.py
  releasenotes/notes/fix-runtime-numpy-result-7b096392ccd35718.yaml
  test/ibm/runtime/test_runtime.py
Labels: Changelog: Bugfix, backport potential

#161 Read runtime programs from "programs" array in response
  qiskit_ibm/api/clients/runtime.py
  qiskit_ibm/api/rest/runtime.py
  qiskit_ibm/runtime/ibm_runtime_service.py
  test/ibm/runtime/fake_runtime_client.py
Labels: backport potential
