Repository Qiskit/qiskit-ibm-provider, pull requests merged in 2021-09, with the labels that each got.

#58 Remove db_filter parameter in `IBMQBackendService.jobs()`
  qiskit_ibm/ibmqbackend.py
  qiskit_ibm/ibmqbackendservice.py
  qiskit_ibm/jupyter/jobs_widget.py
  qiskit_ibm/managed/managedjob.py
  releasenotes/notes/remove-db-filter-7cb403d4dcfa52b2.yaml
  test/ibmq/test_ibmq_job.py
  test/ibmq/test_ibmq_job_attributes.py
Labels: Changelog: Removal

#50 Restore integer dictionary keys dumped by RuntimeEncoder
  qiskit_ibm/runtime/utils.py
  releasenotes/notes/fix-restore-dict-int-keys-c56f8f9bd0279aca.yaml
  test/ibmq/runtime/test_runtime.py
Labels: Changelog: Bugfix

#60 Remove IBMQBackend `retrieve_job()` and `jobs()` methods, use corresponding methods in IBMQBackendService instead
  docs/tutorials/1_the_ibm_quantum_account.ipynb
  qiskit_ibm/ibm_backend.py
  qiskit_ibm/jupyter/jobs_widget.py
  qiskit_ibm/managed/ibm_job_manager.py
  qiskit_ibm/managed/managedjob.py
  releasenotes/notes/remove-backend-methods-5dd007166394906f.yaml
  test/ibm/test_basic_server_paths.py
  test/ibm/test_ibm_backend.py
  test/ibm/test_ibm_integration.py
  test/ibm/test_ibm_job.py
  test/ibm/test_ibm_job_attributes.py
  test/ibm/test_jupyter.py
  test/ibm/test_serialization.py
Labels: Changelog: Removal

#75 Rename IBMBackendService `retrieve_job` method to `job`
  docs/tutorials/1_the_ibm_quantum_account.ipynb
  qiskit_ibm/ibm_backend.py
  qiskit_ibm/ibm_backend_service.py
  releasenotes/notes/rename-retrieve-job-2b2ca77bd6ffa33e.yaml
  test/ibm/test_basic_server_paths.py
  test/ibm/test_ibm_backend.py
  test/ibm/test_ibm_integration.py
  test/ibm/test_ibm_job.py
  test/ibm/test_ibm_job_attributes.py
  test/ibm/test_ibm_jobmanager.py
  test/ibm/test_serialization.py
Labels: Changelog: API Change

#76 Allow user to select runtime image
  qiskit_ibm/api/clients/runtime.py
  qiskit_ibm/api/rest/runtime.py
  qiskit_ibm/runtime/ibm_runtime_service.py
  qiskit_ibm/runtime/runtime_job.py
  releasenotes/notes/support-runtime-image-selection-e2c26cac76e79b55.yaml
  test/ibm/runtime/fake_runtime_client.py
  test/ibm/runtime/test_runtime.py
Labels: Changelog: New Feature

#63 Replace job manager with backend.run()
  MIGRATING.md
  Makefile
  docs/apidocs/ibm-provider.rst
  docs/apidocs/ibm_managed.rst
  docs/tutorials/1_the_ibm_quantum_account.ipynb
  qiskit_ibm/__init__.py
  qiskit_ibm/ibm_backend.py
  qiskit_ibm/ibm_backend_service.py
  qiskit_ibm/job/__init__.py
  qiskit_ibm/job/constants.py
  qiskit_ibm/job/exceptions.py
  qiskit_ibm/job/ibm_circuit_job.py
  qiskit_ibm/job/ibm_composite_job.py
  qiskit_ibm/job/ibm_job.py
  qiskit_ibm/job/sub_job.py
  qiskit_ibm/job/utils.py
  qiskit_ibm/managed/__init__.py
  qiskit_ibm/managed/exceptions.py
  qiskit_ibm/managed/ibm_job_manager.py
  qiskit_ibm/managed/managedjob.py
  qiskit_ibm/managed/managedjobset.py
  qiskit_ibm/managed/managedresults.py
  qiskit_ibm/managed/utils.py
  releasenotes/notes/composite-job-767c61a18255ae92.yaml
  test/fake_account_client.py
  test/ibm/test_basic_server_paths.py
  test/ibm/test_composite_job.py
  test/ibm/test_ibm_job.py
  test/ibm/test_ibm_job_attributes.py
  test/ibm/test_ibm_jobmanager.py
  test/utils.py
Labels: Changelog: API Change

#95 Convert runtime job_id and backend methods to properties
  qiskit_ibm/runtime/runtime_job.py
  releasenotes/notes/convert-runtime-methods-5d5d76f4d20332f1.yaml
  test/ibm/runtime/test_runtime.py
  test/ibm/runtime/test_runtime_integration.py
Labels: Changelog: API Change

#105 Add parent ID support for experiments
  qiskit_ibm/api/clients/experiment.py
  qiskit_ibm/api/rest/root.py
  qiskit_ibm/experiment/ibm_experiment_service.py
  releasenotes/notes/experiments-parent-id-support-1e52d5f6a079c47a.yaml
  test/ibm/experiment/test_experiment_server_integration.py
Labels: Changelog: New Feature
